### ISSUE TITLE
Capture::Tiny leaves temp files behind

### ISSUE THREAD

**Issue by ggl** [dagolden/Capture-Tiny#46] opened 2016-08-03 13:45 UTC
Capture::Tiny leaves $TMPDIR littered with temporary files under Linux.

**Comment by xdg** [comment] 2016-08-04 02:38
This looks like a duplicate of #45.  If you can give complete steps to replicate or can do your own diagnosis of the underlying issue, please let me know.

**Closed** 2016-08-05 17:39 UTC
